// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type ObtainedMarks struct {
	Roll   int    `json:"Roll"`
	Name   string `json:"Name"`
	Course string `json:"Course"`
	Sem1   int    `json:"Sem1"`
	Sem2   int    `json:"Sem2"`
	Sem3   int    `json:"Sem3"`
	Total  int    `json:"Total"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type EnterDetails struct {
	Name   string   `json:"Name"`
	Course []string `json:"Course"`
}

type Inputcourses struct {
	X int    `json:"x"`
	Y string `json:"y"`
}

type Inputdynamic struct {
	Arr []*int `json:"arr"`
}

type Inputstr struct {
	X int    `json:"x"`
	Y string `json:"y"`
	P string `json:"p"`
}

type Inputstr1 struct {
	Roll   int    `json:"roll"`
	Course string `json:"course"`
	Sem1   int    `json:"sem1"`
	Sem2   int    `json:"sem2"`
	Sem3   int    `json:"sem3"`
}

type Inputstr2 struct {
	Roll int    `json:"roll"`
	Name string `json:"name"`
}

type Inputvalues struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type Inputvalues1 struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type Marks struct {
	X  int    `json:"x"`
	Y  int    `json:"y"`
	Z  int    `json:"z"`
	Ro int    `json:"ro"`
	C  string `json:"c"`
}

type Outpurcourses struct {
	Z []*string `json:"z"`
}

type Outputdynamic struct {
	A *int `json:"a"`
	B *int `json:"b"`
	C *int `json:"c"`
	D *int `json:"d"`
	E *int `json:"e"`
	F *int `json:"f"`
}

type Outputstr struct {
	Z string `json:"z"`
}

type Outputstr1 struct {
	Total int `json:"total"`
}

type Outputstr2 struct {
	Result string `json:"result"`
}

type Outputvalues struct {
	Z string `json:"z"`
}

type Outputvalues1 struct {
	Z []*string `json:"z"`
}

type Showdetails struct {
	Details []*ObtainedMarks `json:"details"`
}

type Student struct {
	Roll   int    `json:"roll"`
	Name   string `json:"name"`
	Course string `json:"course"`
	Total  int    `json:"total"`
}

type Testmarks struct {
	Roll int `json:"roll"`
}

type Testtotal struct {
	Marks []*Student `json:"marks"`
}

type Total struct {
	T int `json:"t"`
}
